### PR TITLE
feat(favicon): add favicon to default layout

### PR DESCRIPTION
**Pull request by dvdzkwsk**

### CODE REVIEW

**Comment by ghost** [comment]
:shipit:

**Comment by d2s** [comment]
New favicon looks solid.
Image of TA logo

Though it is a bit different (better...) than the current one on the main [TechnologyAdvice](http://technologyadvice.com/) site.
Image of TA logo

There is also a difference in how the main site

``` html
<link rel="icon" href="http://technologyadvice.com/wp-content/themes/techadvice/favicon.png">
```

and the developer blog (in this Pull Request) implement the HTML markup.

``` html
<link rel="shortcut icon" href="https://s3.amazonaws.com/ta-design/Assets/favicon-32x32.png"></link>
```

It appears that in addition the blog, main site of the service could be updated with the new updated logo?

**Comment by ksafranski** [comment]
@d2s thanks for the input! This blog is really new (only about a month) and we'll be working with out internal marketing team to align assets like this in the coming weeks. This is more of a "so we have a favicon" PR :smile:

**Comment by ghost** [comment]
It is so. 2016

**Pull request merged**
