### PR TITLE
DevLab 1.7 - Links and Exec on Services

### PR DESCRIPTION
**Pull request by ksafranski**

### CODE REVIEW

**Comment by ghost** [comment]
Allowing composition through LINK is awesome! Aside from order of operations, any special considerations for placement of LINKs WRT caching and intermediate containers?

**Comment by ksafranski** [comment]
Nope, pretty simple implementation, no affect on any other part of the workflow. `exec` failures will result in the services being stopped just as if you had completed a task but that seems like a pretty expected behavior.

**Comment by ksafranski** [comment]
Any changes or edits? I'd like to post this today since I dropped 1.7 on Friday :smile:

**Comment by ghost** [comment]
None here. :shipit:

**Pull request merged**
